# Site settings
title: Or Cherfas
email: or@orcherfas.com
description: Or Cherfas personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orcherfas.com" # the base hostname & protocol for your site

# Identity
your-name: Or Cherfas
your-title: Experienced Software Developer

# Social settings
github_url: https://github.com/ocherfas
linkedin_url: https://www.linkedin.com/in/or-cherfas

# Build settings
markdown: kramdown
